### PR TITLE
Back port issue 700 fix

### PR DESCRIPTION
**Pull request by YuryAndr**
Back port for https://github.com/rabbitmq/rabbitmq-java-client/pull/701

### CODE REVIEW

**Review by michaelklishin — APPROVED** [review]

**Comment by michaelklishin** [comment]
@YuryAndr thank you. May I ask you to submit the same thing against `5.13.x-stable` as well?

It's a very PTO heavy week on our team but we should be able to produce a release in the next few days.

**Comment by YuryAndr** [comment]
@michaelklishin It was already provided for 5.13.x-stable by @acogoluegnes

**Comment by acogoluegnes** [comment]
It's indeed already backported to 5.13.x-stable. Backporting to 5.7.x is not necessary because we will not release any 5.7.x now, it's only 5.13.1 or 5.14.0. Moving from 5.7.x to 5.13.x or 5.14.x should have no impact.

**Comment by YuryAndr** [comment]
@acogoluegnes Ok. We will move to 5.13.1 and try to test some corner cases. Thanks!

**Comment by acogoluegnes** [comment]
Have you tried the 5.13.1 snapshot? If you're fine with it, I can release 5.13.1 in the next few days and make the announcement later.

**Comment by YuryAndr** [comment]
@acogoluegnes Yes it looks working fine for our cases. Please, release 5.13.1

**Comment by acogoluegnes** [comment]
5.13.1 is released.

**Comment by YuryAndr** [comment]
Thank you!

**Pull request merged**
