### PR TITLE
Add excludeQueueFromRecovery method

### PR DESCRIPTION
**Pull request by vikinghawk**
## Proposed Changes

See #345 for details. As requested creating this new PR on 4.x.x branch. Renamed method and added test,

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes issue #NNNN)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] All tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

## Further Comments

If this is a relatively large or complex change, kick off the discussion by
explaining why you chose the solution you did and what alternatives you
considered, etc.

### CODE REVIEW

**Comment by michaelklishin** [comment]
Thank you!

**Comment by vikinghawk** [comment]
do you guys have any estimate on when this and #343 might be released on 4.x?

Its not super urgent, but would be much appreciated by either 2/6 or 3/6 so we can get it into one of our next releases. Thanks!

**Comment by michaelklishin** [comment]
Within a week sounds doable.

**Comment by acogoluegnes** [comment]
@vikinghawk 4.5.0.RC1 has just been released.

**Pull request merged**
