### PR TITLE
implements java.io.Closeable

### PR DESCRIPTION
**Pull request by xuwei-k**

### CODE REVIEW

**Comment by michaelklishin** [comment]
Thank you. This means giving up JDK 6 compatibility. We are not ready to do that just yet.

**Comment by xuwei-k** [comment]
http://docs.oracle.com/javase/6/docs/api/java/io/Closeable.html

`java.io.Closeable` exists since java 1.5

**Comment by michaelklishin** [comment]
Right, I thought of `Autocloseable`.

**Comment by michaelklishin** [comment]
Thank you!

**Comment by michaelklishin** [comment]
I had to revert this because it conflicts with #46  (damn checked exceptions).

**Pull request merged**
