### PR TITLE
Switch from Ant to Maven

### LINKED ISSUE #166: Backport Maven-based build toolchain to stable
In part to get a fix for #162 into `stable`, in part to not have to use two different toolchains.

### PR DESCRIPTION
**Pull request by dumbbell**
This is a backport of what was done in the `master` branch, starting with commit c2cd9f3fc342077b963bc2a0a9b5f5948e1ec1db.

Fixes #166.
[#128048833]

### CODE REVIEW

**Comment by michaelklishin** [comment]
`mvn verify` didn't start a node for me:

```
deps/rabbitmq_java_client/ backport-migration-to-maven mvn verify
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building RabbitMQ Java Client 3.6.6-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- groovy-maven-plugin:2.0:execute (generate-amqp-sources) @ amqp-client ---
[INFO]
[INFO] --- build-helper-maven-plugin:1.12:add-source (add-generated-sources-dir) @ amqp-client ---
[INFO] Source directory: /Users/antares/Development/RabbitMQ/stable_umbrella.git/deps/rabbitmq_java_client/target/generated-sources/src/main/java added.
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ amqp-client ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ amqp-client ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-bundle-plugin:2.3.7:manifest (bundle-manifest) @ amqp-client ---
[INFO]
[INFO] --- groovy-maven-plugin:2.0:execute (remove-old-test-keystores) @ amqp-client ---
[INFO]
[INFO] --- keytool-maven-plugin:1.5:importCertificate (generate-test-ca-keystore) @ amqp-client ---
[INFO] Disabled
[INFO]
[INFO] --- keytool-maven-plugin:1.5:importCertificate (generate-test-empty-keystore) @ amqp-client ---
[INFO] Disabled
[INFO]
[INFO] --- keytool-maven-plugin:1.5:deleteAlias (generate-test-empty-keystore) @ amqp-client ---
[INFO] Disabled
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:testResources (default-testResources) @ amqp-client ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ amqp-client ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ amqp-client ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-jar-plugin:3.0.2:jar (default-jar) @ amqp-client ---
[INFO] Building jar: /Users/antares/Development/RabbitMQ/stable_umbrella.git/deps/rabbitmq_java_client/target/amqp-client-3.6.6-SNAPSHOT.jar
[INFO]
[INFO] --- maven-failsafe-plugin:2.19.1:integration-test (integration-test) @ amqp-client ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.rabbitmq.client.test.ClientTests
Tests run: 50, Failures: 0, Errors: 19, Skipped: 0, Time elapsed: 1.287 sec <<< FAILURE! - in com.rabbitmq.client.test.ClientTests
testClientProvidedConnectionName(com.rabbitmq.client.test.AMQConnectionTest)  Time elapsed: 0.027 sec  <<< ERROR!
java.net.ConnectException: Connection refused
	at com.rabbitmq.client.test.AMQConnectionTest.testClientProvidedConnectionName(AMQConnectionTest.java:181)

testBug20004(com.rabbitmq.client.test.Bug20004Test)  Time elapsed: 0.001 sec  <<< ERROR!
java.net.ConnectException: Connection refused

testCloseWithFaultyConsumer(com.rabbitmq.client.test.CloseInMainLoop)  Time elapsed: 0.001 sec  <<< ERROR!
java.net.ConnectException: Connection refused

testCloseOKNormallyReceived(com.rabbitmq.client.test.CloseInMainLoop)  Time elapsed: 0.003 sec  <<< ERROR!
java.net.ConnectException: Connection refused

testReserveOnBoundaries(com.rabbitmq.client.test.ChannelNumberAllocationTests)  Time elapsed: 0.002 sec  <<< ERROR!
java.net.ConnectException: Connection refused
	at com.rabbitmq.client.test.ChannelNumberAllocationTests.setUp(ChannelNumberAllocationTests.java:42)

testAllocateAfterFreeingLast(com.rabbitmq.client.test.ChannelNumberAllocationTests)  Time elapsed: 0.002 sec  <<< ERROR!
java.net.ConnectException: Connection refused
	at com.rabbitmq.client.test.ChannelNumberAllocationTests.setUp(ChannelNumberAllocationTests.java:42)

testAllocateAfterFreeingMany(com.rabbitmq.client.test.ChannelNumberAllocationTests)  Time elapsed: 0.002 sec  <<< ERROR!
java.net.ConnectException: Connection refused
	at com.rabbitmq.client.test.ChannelNumberAllocationTests.setUp(ChannelNumberAllocationTests.java:42)

testManualAllocationDoesntBreakThings(com.rabbitmq.client.test.ChannelNumberAllocationTests)  Time elapsed: 0.001 sec  <<< ERROR!
java.net.ConnectException: Connection refused
	at com.rabbitmq.client.test.ChannelNumberAllocationTests.setUp(ChannelNumberAllocationTests.java:42)

testAllocateAfterManualAssign(com.rabbitmq.client.test.ChannelNumberAllocationTests)  Time elapsed: 0.002 sec  <<< ERROR!
java.net.ConnectException: Connection refused
	at com.rabbitmq.client.test.ChannelNumberAllocationTests.setUp(ChannelNumberAllocationTests.java:42)

testReuseManuallyAllocatedChannelNumber1(com.rabbitmq.client.test.ChannelNumberAllocationTests)  Time elapsed: 0.001 sec  <<< ERROR!
java.net.ConnectException: Connection refused
	at com.rabbitmq.client.test.ChannelNumberAllocationTests.setUp(ChannelNumberAllocationTests.java:42)

testReuseManuallyAllocatedChannelNumber2(com.rabbitmq.client.test.ChannelNumberAllocationTests)  Time elapsed: 0.003 sec  <<< ERROR!
java.net.ConnectException: Connection refused
	at com.rabbitmq.client.test.ChannelNumberAllocationTests.setUp(ChannelNumberAllocationTests.java:42)

testAllocateInOrder(com.rabbitmq.client.test.ChannelNumberAllocationTests)  Time elapsed: 0.001 sec  <<< ERROR!
java.net.ConnectException: Connection refused
	at com.rabbitmq.client.test.ChannelNumberAllocationTests.setUp(ChannelNumberAllocationTests.java:42)

testNThreadShutdown(com.rabbitmq.client.test.QueueingConsumerShutdownTests)  Time elapsed: 0.001 sec  <<< ERROR!
java.net.ConnectException: Connection refused

testInterleavedRpcs(com.rabbitmq.client.test.MultiThreadedChannel)  Time elapsed: 0.001 sec  <<< ERROR!
java.net.ConnectException: Connection refused

testParticularBuilderForBasicSanityWithRpc(com.rabbitmq.client.test.AMQBuilderApiTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.net.ConnectException: Connection refused

testIllFormedBuilder(com.rabbitmq.client.test.AMQBuilderApiTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.net.ConnectException: Connection refused

testParticularBuilderForBasicSanityWithAsyncRpc(com.rabbitmq.client.test.AMQBuilderApiTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.net.ConnectException: Connection refused

testUriParsing(com.rabbitmq.client.test.AmqpUriTest)  Time elapsed: 0 sec  <<< ERROR!
java.net.ConnectException: Connection refused

testWillShutDownExecutor(com.rabbitmq.client.test.SharedThreadPoolTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.net.ConnectException: Connection refused
```

and running it against a `make run-broker` node doesn't progress as soon as it gets to the functional suite (there is no activity in server logs).

**Comment by michaelklishin** [comment]
I can reproduce this on Linux. Here's `jstack` output:

```
jstack 14302
2016-08-11 14:59:21
Full thread dump OpenJDK 64-Bit Server VM (25.91-b14 mixed mode):

"Attach Listener" #24 daemon prio=9 os_prio=0 tid=0x00007f0e80001000 nid=0x428b waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Thread-3" #22 prio=5 os_prio=0 tid=0x00007f0ead28b800 nid=0x3819 runnable [0x00007f0e63a5f000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:255)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	- locked <0x00000000f6b77a68> (a java.lang.UNIXProcess$ProcessPipeInputStream)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	- locked <0x00000000f6ba5a58> (a java.io.InputStreamReader)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	- locked <0x00000000f6ba5a58> (a java.io.InputStreamReader)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at org.apache.maven.surefire.shade.org.apache.maven.shared.utils.cli.StreamPumper.run(StreamPumper.java:76)

"Thread-2" #21 prio=5 os_prio=0 tid=0x00007f0ead28a800 nid=0x3818 runnable [0x00007f0e63b60000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:255)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	- locked <0x00000000f6b759a8> (a java.lang.UNIXProcess$ProcessPipeInputStream)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	- locked <0x00000000f6ba2dc8> (a java.io.InputStreamReader)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	- locked <0x00000000f6ba2dc8> (a java.io.InputStreamReader)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at org.apache.maven.surefire.shade.org.apache.maven.shared.utils.cli.StreamPumper.run(StreamPumper.java:76)

"Thread-1" #20 prio=5 os_prio=0 tid=0x00007f0eac14d800 nid=0x3816 waiting on condition [0x00007f0e63c61000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000f66621f0> (a java.util.concurrent.Semaphore$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.Semaphore.acquire(Semaphore.java:312)
	at org.apache.maven.plugin.surefire.booterclient.lazytestprovider.TestLessInputStream.awaitNextCommand(TestLessInputStream.java:156)
	at org.apache.maven.plugin.surefire.booterclient.lazytestprovider.TestLessInputStream.beforeNextCommand(TestLessInputStream.java:127)
	at org.apache.maven.plugin.surefire.booterclient.lazytestprovider.AbstractCommandStream.read(AbstractCommandStream.java:101)
	at org.apache.maven.surefire.shade.org.apache.maven.shared.utils.cli.StreamFeeder.feed(StreamFeeder.java:123)
	at org.apache.maven.surefire.shade.org.apache.maven.shared.utils.cli.StreamFeeder.run(StreamFeeder.java:60)

"ThreadedStreamConsumer" #19 daemon prio=5 os_prio=0 tid=0x00007f0ead280000 nid=0x3814 waiting on condition [0x00007f0e63efd000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000f677cae8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at org.apache.maven.plugin.surefire.booterclient.output.ThreadedStreamConsumer$Pumper.run(ThreadedStreamConsumer.java:71)
	at java.lang.Thread.run(Thread.java:745)

"ping-timer-10sec" #16 daemon prio=5 os_prio=0 tid=0x00007f0ead292800 nid=0x3813 waiting on condition [0x00007f0e63ffe000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000f65adc10> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"resolver-4" #15 daemon prio=5 os_prio=0 tid=0x00007f0eadc63800 nid=0x3812 waiting on condition [0x00007f0e63d62000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000d0b56fe0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"resolver-3" #14 daemon prio=5 os_prio=0 tid=0x00007f0eadc62800 nid=0x3811 waiting on condition [0x00007f0e8415e000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000d0b56fe0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"resolver-2" #13 daemon prio=5 os_prio=0 tid=0x00007f0eadc48800 nid=0x380e waiting on condition [0x00007f0e851b1000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000d0b56fe0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"resolver-1" #12 daemon prio=5 os_prio=0 tid=0x00007f0ead7fa800 nid=0x380d waiting on condition [0x00007f0e850b0000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000d0b56fe0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"process reaper" #9 daemon prio=10 os_prio=0 tid=0x00007f0ead8e0000 nid=0x3809 runnable [0x00007f0e86244000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.UNIXProcess.waitForProcessExit(Native Method)
	at java.lang.UNIXProcess.lambda$initStreams$3(UNIXProcess.java:290)
	at java.lang.UNIXProcess$$Lambda$7/918606013.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"Service Thread" #7 daemon prio=9 os_prio=0 tid=0x00007f0eac0af000 nid=0x3803 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread1" #6 daemon prio=9 os_prio=0 tid=0x00007f0eac0ac000 nid=0x3802 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=0 tid=0x00007f0eac0a9000 nid=0x3801 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 tid=0x00007f0eac0a7000 nid=0x3800 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=0 tid=0x00007f0eac07f800 nid=0x37ff in Object.wait() [0x00007f0e9c4f3000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000d07f4948> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x00000000d07f4948> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=0 tid=0x00007f0eac07b000 nid=0x37fe in Object.wait() [0x00007f0e9c5f4000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000d0845a80> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x00000000d0845a80> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"main" #1 prio=5 os_prio=0 tid=0x00007f0eac00a000 nid=0x37fa in Object.wait() [0x00007f0eb62c3000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000f6b73700> (a java.lang.UNIXProcess)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.UNIXProcess.waitFor(UNIXProcess.java:396)
	- locked <0x00000000f6b73700> (a java.lang.UNIXProcess)
	at org.apache.maven.surefire.shade.org.apache.maven.shared.utils.cli.CommandLineUtils$1.call(CommandLineUtils.java:260)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:550)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:460)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:229)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:201)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1026)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:862)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:755)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

"VM Thread" os_prio=0 tid=0x00007f0eac073800 nid=0x37fd runnable 

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x00007f0eac01f000 nid=0x37fb runnable 

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x00007f0eac021000 nid=0x37fc runnable 

"VM Periodic Task Thread" os_prio=0 tid=0x00007f0eac0b5800 nid=0x3804 waiting on condition 

JNI global references: 296
```

and `ps aux | grep java`:

```
ps aux | grep java
antares   14302 15.7 12.9 3245972 404816 pts/6  Sl+  14:56   0:20 /usr/lib/jvm/java-8-openjdk-amd64/bin/java -classpath /usr/share/maven/boot/plexus-classworlds-2.x.jar -Dclassworlds.conf=/usr/share/maven/bin/m2.conf -Dmaven.home=/usr/share/maven -Dmaven.multiModuleProjectDirectory=/home/antares/git/stable_umbrella.git/deps/rabbitmq_java_client org.codehaus.plexus.classworlds.launcher.Launcher verify
antares   14357  0.0  0.0   4512   788 pts/6    S+   14:56   0:00 /bin/sh -c cd /home/antares/git/stable_umbrella.git/deps/rabbitmq_java_client && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -jar /home/antares/git/stable_umbrella.git/deps/rabbitmq_java_client/target/surefire/surefirebooter6776809575216572749.jar /home/antares/git/stable_umbrella.git/deps/rabbitmq_java_client/target/surefire/surefire8667671926581079443tmp /home/antares/git/stable_umbrella.git/deps/rabbitmq_java_client/target/surefire/surefire_0708289059678398684tmp
antares   14359 14.5  9.2 3208660 288108 pts/6  Sl+  14:56   0:17 /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -jar /home/antares/git/stable_umbrella.git/deps/rabbitmq_java_client/target/surefire/surefirebooter6776809575216572749.jar /home/antares/git/stable_umbrella.git/deps/rabbitmq_java_client/target/surefire/surefire8667671926581079443tmp /home/antares/git/stable_umbrella.git/deps/rabbitmq_java_client/target/surefire/surefire_0708289059678398684tmp
antares   16625  0.0  0.0   4512   752 pts/6    S+   14:58   0:00 /bin/sh -c make -C '/home/antares/git/stable_umbrella.git/deps/rabbitmq_java_client/../rabbit' RABBITMQCTL='/home/antares/git/stable_umbrella.git/deps/rabbitmq_java_client/../rabbit/scripts/rabbitmqctl' RABBITMQ_NODENAME='rabbit@localhost' RABBITMQ_NODE_PORT=5672 RABBITMQ_CONFIG_FILE='/home/antares/git/stable_umbrella.git/deps/rabbitmq_java_client/target/test-classes/rabbit@localhost' stop-rabbit-on-node start-rabbit-on-node
antares   16627  0.0  0.1  10352  3320 pts/6    S+   14:58   0:00 make -C /home/antares/git/stable_umbrella.git/deps/rabbitmq_java_client/../rabbit RABBITMQCTL=/home/antares/git/stable_umbrella.git/deps/rabbitmq_java_client/../rabbit/scripts/rabbitmqctl RABBITMQ_NODENAME=rabbit@localhost RABBITMQ_NODE_PORT=5672 RABBITMQ_CONFIG_FILE=/home/antares/git/stable_umbrella.git/deps/rabbitmq_java_client/target/test-classes/rabbit@localhost stop-rabbit-on-node start-rabbit-on-node
antares   16772  0.0  0.0   4512   708 pts/6    S+   14:58   0:00 /bin/sh -c ERL_LIBS="/home/antares/git/stable_umbrella.git/deps/rabbit/apps" \   /home/antares/git/stable_umbrella.git/deps/rabbitmq_java_client/../rabbit/scripts/rabbitmqctl -n rabbit@localhost wait /tmp/rabbitmq-test-instances/rabbit@localhost/rabbit@localhost.pid
```

**Comment by acogoluegnes** [comment]
Looks like the `setup-test-cluster` profile isn't activated. Right now, the activation conditions are:

```xml
<activation>
  <property>
    <name>!skipTests</name>
  </property>
  <file>
    <exists>${rabbitmq.dir}</exists>
  </file>
</activation>
```

But the [Maven documentation](http://maven.apache.org/guides/introduction/introduction-to-profiles.html) for the `file` tags says:

> Please note that properties and values defined in the POM itself are not available for interpolation

I tried with an hard-coded path and it worked (HA and client tests).

The following Maven target can also help to identify the activated profiles:

```
mvn help:active-profiles
```

We have to find something else to activate the cluster setup profile.

**Comment by acogoluegnes** [comment]
Just want to confirm that `FunctionalTests` are hanging. But `HATests` (which include `FunctionalTests`) are working:

```
mvn verify -Dit.test=HATests -P setup-test-cluster
```

Weird. Maybe something in the setUp/tearDown sequence.

**Comment by acogoluegnes** [comment]
The `setup-test-cluster` profile is always activated with Maven 3.0.5, but it's not with Maven 3.2.x. The idea would be to enable it by default and disable it explicitly.

**Pull request merged**
