### PR TITLE
Adds required command line args to GraalVM native-image command.

### PR DESCRIPTION
**Pull request by rjbaucells**
## Proposed Changes

GraalVM native image generation requires all resources to be explicitly added to the final image using the command line argument `-H:IncludeResources=resource1|resource2|...|resourceN`.

Libraries can specify the required command line arguments to the `native-image` command by creating a resource in the following location:

```
META-INF/native-image/${groupId}/${artifactId}/native-image.properties
```

See [Native Image Build Configuration](https://www.graalvm.org/reference-manual/native-image/BuildConfiguration/) documentation for more details.

## Types of Changes

What types of changes does your code introduce to this project?

- [ ] Bugfix (non-breaking change which fixes issue #NNNN)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [X] I have read the `CONTRIBUTING.md` document
- [X] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [X] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@rjbaucells Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-java-client&pullRequestId=666)!

**Review by michaelklishin — APPROVED** [review]

**Comment by michaelklishin** [comment]
Thank you!

**Comment by michaelklishin** [comment]
This can be backported and included into a patch release if necessary. Let us know.

**Comment by rjbaucells** [comment]
I think it is a good idea to port it to `5.10.X` release so it is available now. I can do a PR if needed, just let me know the branch I should as target for the PR.

**Comment by acogoluegnes** [comment]
We should release 5.11.0.RC1 pretty soon (hopefully this week).

**Pull request merged**
