### PR TITLE
During handshake, await on continuations with a timeout

### PR DESCRIPTION
**Pull request by michaelklishin**
References #65.

### CODE REVIEW

**Comment by jhalterman** [comment]
Using the makefile to build, I hit a compile error with this change:

```
    [javac] /Users/jonathan/dev/rabbitmq-java-client/src/com/rabbitmq/client/impl/recovery/RecoveryAwareAMQConnectionFactory.java:36: unreported exception java.util.concurrent.TimeoutException; must be caught or declared to be thrown
    [javac]                 conn.start();
```

**Comment by michaelklishin** [comment]
@jhalterman ok, should compile from scratch now.

```
ant clean && ant dist
```

is how you build a full jar.

**Comment by jhalterman** [comment]
:+1:

**Comment by michaelklishin** [comment]
Will merge manually into stable.

**Comment by michaelklishin** [comment]
@jhalterman thanks for confirming!

**Comment by jhalterman** [comment]
Thanks for the quick fix!

**Pull request closed without merging**
