### PR TITLE
Add RpcClient doCall/responseCall/primitiveCall overloads which include timeout

### PR DESCRIPTION
**Pull request by AndreasPresthammer**
## Proposed Changes

There will be use cases where a single shared timeout specified in the constructor
of the RpcClient will not match up with the expected timeout for different rpc calls
made using the rpc client. It's then convenient to be able to specifiy the timeout value
on a per method call basis. Otherwise the user of RpcClient would have to create
multiple instances of RpcClient, incurring the startup cost and having redundant
consumers of the response queue.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes issue #NNNN)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask on the
mailing list. We're here to help! This is simply a reminder of what we are
going to look for before merging your code._

- [ x] I have read the `CONTRIBUTING.md` document
- [ ] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

Note:
Unable to run the tests locally with 'make tests'. Getting this error:

[ERROR] Failed to execute goal org.codehaus.gmaven:groovy-maven-plugin:2.0:execute (query-test-tls-certs-dir) on project amqp-client: Execution query-test-tls-certs-dir of goal org.codehaus.gmaven:groovy-maven-plugin:2.0:execute failed: org.apache.maven.plugin.MojoExecutionException: Failed to query test TLS certs directory with command: make -C /home/andreas/code/rabbitmq-java-client/deps/rabbit --no-print-directory show-test-tls-certs-dir DEPS_DIR=/home/andreas/code/rabbitmq-java-client/deps -> [Help 1]

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@AndreasPresthammer Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-java-client&pullRequestId=338)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-java-client&pullRequestId=338) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by michaelklishin** [comment]
@acogoluegnes this looks like a reasonable addition to me, even though we use `RpcClient` mostly as an example. WDYT?

**Comment by acogoluegnes** [comment]
@michaelklishin LGTM. @AndreasPresthammer Could you please sign the contributor licence agreement?

**Comment by AndreasPresthammer** [comment]
Have to check with legal at my employer. Hopefully shouldn't take too long.

**Comment by acogoluegnes** [comment]
@AndreasPresthammer Any news on the CA signature?

**Comment by pivotal-issuemaster** [comment]
@AndreasPresthammer Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-java-client&pullRequestId=338)!

**Comment by AndreasPresthammer** [comment]
I've signed the CLA.

**Comment by michaelklishin** [comment]
@acogoluegnes looks like we can back port this all the way to `4.x`?

**Comment by acogoluegnes** [comment]
@michaelklishin Yes, looks good.

**Comment by acogoluegnes** [comment]
@michaelklishin But only in `4.x.x-stable` (4.5.0), as this is a new feature.

**Comment by acogoluegnes** [comment]
Cherry-picked on `4.x.x-stable`, will be available in 4.5.0.

**Pull request merged**
