### PR TITLE
Switch to NIO

### LINKED ISSUE #11: Switch to NIO[2]
Reported and discussed in some depth on [rabbitmq-discuss](http://rabbitmq.1065348.n5.nabble.com/Long-timeout-if-server-host-becomes-unreachable-td30275.html).

Internal bug tracker: `#23327`.

The only solution is switching to NIO. NIO would yield little improvement for the client the way it works today but worth moving to for this issue.

### PR DESCRIPTION
**Pull request by acogoluegnes**
Fixes #11

### CODE REVIEW

**Comment by michaelklishin** [comment]
This fails CI and no longer merges cleanly.

**Comment by michaelklishin** [comment]
With the recent EOF handling fix, the CPU/Heap/Threads charts in Visual VM over the course of a test suite run now look nearly identical with the default profile vs. use-nio. This is looking good for inclusion as an opt-in feature for `4.0.0`.

**Comment by michaelklishin** [comment]
I observe a couple of test failures in TLS with NIO enabled:

```
17:25:51.472 [main] INFO  c.r.client.test.BrokerTestCase - Test finished: NioTlsUnverifiedConnection.connectionGetConsume
Tests run: 8, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.392 sec <<< FAILURE! - in com.rabbitmq.client.test.ssl.SSLTests
sSL(com.rabbitmq.client.test.ssl.VerifiedConnection)  Time elapsed: 0.232 sec  <<< FAILURE!
java.lang.AssertionError: Couldn't open TLS connection after 3 attemps
	at com.rabbitmq.client.test.ssl.VerifiedConnection.openConnection(VerifiedConnection.java:99)

sSL(com.rabbitmq.client.test.ssl.VerifiedConnection)  Time elapsed: 0.232 sec  <<< FAILURE!
java.lang.AssertionError: Couldn't open TLS connection after 3 attemps
	at com.rabbitmq.client.test.ssl.VerifiedConnection.openConnection(VerifiedConnection.java:99)


Results :

Failed tests:
com.rabbitmq.client.test.ssl.VerifiedConnection.sSL(com.rabbitmq.client.test.ssl.VerifiedConnection)
  Run 1: VerifiedConnection>BrokerTestCase.setUp:71->openConnection:99 Couldn't open TLS connection after 3 attemps
  Run 2: VerifiedConnection>BrokerTestCase.tearDown:82->openConnection:99 Couldn't open TLS connection after 3 attemps
```

(on OS X)

**Comment by acogoluegnes** [comment]
The TLS handshake failures are likely to happen with Erlang 19.x. It's been fixed in 19.1.1. These failures are transient, with blocking IO and NIO.

**Comment by michaelklishin** [comment]
Yes, that was it. The suite passes with flying colors on 19.1.1.

**Pull request merged**
