### PR TITLE
ID for PerfTest jobs and Unique system out for better output in multithreading.

### PR DESCRIPTION
**Pull request by abousselmi**
Dear reviewer,
I added an ID variable to PerfTest.java to identify each running test.
I also modified the System.out to work better when multiple PerfTest threads are running in the same machine.
Best regards,
AB.

### CODE REVIEW

**Comment by michaelklishin** [comment]
I assume this can be released in `3.6.x`? If so, please also submit this against `stable`.

**Comment by michaelklishin** [comment]
Thank you. I am not 100% sure we should ship this in `3.6.x` so it will have to wait for 4.0.0 (née 3.7.0).

**Comment by abousselmi** [comment]
Thank you for your reply. Until then!

**Comment by acogoluegnes** [comment]
@abousselmi maybe you could rename `showRate` to `getRate` now it returns a String and no longer show something in the console?

**Comment by abousselmi** [comment]
It's a good idea! Will do it. Thank you.

**Comment by abousselmi** [comment]
@acogoluegnes I added a test id also to the final output messages, whould it be possible to make a new pull request for it ? Thank you.

**Comment by michaelklishin** [comment]
@abousselmi you can submit a new pull request, sure.

**Comment by abousselmi** [comment]
Thank you for you reply.

**Pull request merged**
